2025-04-06 22:27:50,381 ERROR: Exception on /login [POST] [in C:\pyProj\nir-assistant-ver2\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\pyProj\nir-assistant-ver2\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\pyProj\nir-assistant-ver2\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\pyProj\nir-assistant-ver2\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\pyProj\nir-assistant-ver2\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\pyProj\nir-assistant-ver2\app\routes\auth.py", line 31, in login
    log_entry = LogEntry(
                ^^^^^^^^
NameError: name 'LogEntry' is not defined
2025-04-06 22:30:06,652 ERROR: Exception on /login [POST] [in C:\pyProj\nir-assistant-ver2\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\pyProj\nir-assistant-ver2\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\pyProj\nir-assistant-ver2\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\pyProj\nir-assistant-ver2\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\pyProj\nir-assistant-ver2\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\pyProj\nir-assistant-ver2\app\routes\auth.py", line 31, in login
    log_entry = LogEntry(
                ^^^^^^^^
NameError: name 'LogEntry' is not defined
2025-04-06 22:45:45,778 ERROR: Exception on /login [POST] [in C:\pyProj\nir-assistant-ver2\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\pyProj\nir-assistant-ver2\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\pyProj\nir-assistant-ver2\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\pyProj\nir-assistant-ver2\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\pyProj\nir-assistant-ver2\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\pyProj\nir-assistant-ver2\app\routes\auth.py", line 31, in login
    log_entry = LogEntry(
                ^^^^^^^^
NameError: name 'LogEntry' is not defined
2025-04-06 22:48:17,929 ERROR: Exception on /login [POST] [in C:\pyProj\nir-assistant-ver2\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\pyProj\nir-assistant-ver2\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\pyProj\nir-assistant-ver2\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\pyProj\nir-assistant-ver2\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\pyProj\nir-assistant-ver2\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\pyProj\nir-assistant-ver2\app\routes\auth.py", line 31, in login
    log_entry = LogEntry(
                ^^^^^^^^
NameError: name 'LogEntry' is not defined
2025-04-06 23:20:08,575 INFO: NIR Assistant startup [in C:\pyProj\nir-assistant-ver2\app\__init__.py:72]
2025-04-06 23:28:41,462 INFO: NIR Assistant startup [in c:\pyProj\nir-assistant-ver2\app\__init__.py:72]
2025-04-06 23:28:42,193 INFO: NIR Assistant startup [in c:\pyProj\nir-assistant-ver2\app\__init__.py:72]
2025-04-06 23:29:09,048 INFO: NIR Assistant startup [in c:\pyProj\nir-assistant-ver2\app\__init__.py:72]
2025-04-06 23:29:09,808 INFO: NIR Assistant startup [in c:\pyProj\nir-assistant-ver2\app\__init__.py:72]
2025-04-06 23:48:14,158 INFO: NIR Assistant startup [in C:\pyProj\nir-assistant-ver2\app\__init__.py:72]
2025-04-06 23:53:40,210 INFO: NIR Assistant startup [in C:\pyProj\nir-assistant-ver2\app\__init__.py:72]
2025-04-07 00:15:44,571 INFO: NIR Assistant startup [in C:\pyProj\nir-assistant-ver2\app\__init__.py:72]
2025-04-07 00:24:49,138 INFO: NIR Assistant startup [in C:\pyProj\nir-assistant-ver2\app\__init__.py:72]
2025-04-07 00:32:41,655 INFO: NIR Assistant startup [in C:\pyProj\nir-assistant-ver2\app\__init__.py:72]
2025-04-07 00:36:43,216 INFO: NIR Assistant startup [in C:\pyProj\nir-assistant-ver2\app\__init__.py:72]
2025-04-07 00:41:20,724 INFO: NIR Assistant startup [in C:\pyProj\nir-assistant-ver2\app\__init__.py:72]
